# type: regex, !regex, eq, !eq, sw, !sw, ew, !ew, wc, !wc, ct, !ct
# regex == just regex
# wc == wildcard
# eq == equal
# sw == startwith
# ew == endwith
# ct == contains
# ! == not

################################
#            format            #
################################
# {type} {variable}:
#   taget: {host}:{port}

regex .*:
  taget: 192.168.1.14:2000
  rate_limit: 10/s
